"""Exceptions, at the Selenium 4.x import path
``from selenium.common.exceptions import NoSuchElementException`` (and the rest).

Thin re-export shim: every exception class is defined ONCE in the binding core
(``selenium._webdriver``) — where the engine's W3C error decode maps integer
codes to these types — so there is a single source of truth. This module exists
only so an unmodified upstream script resolves them at the mainstream location,
with the same names and the same base-class hierarchy.
"""

from .._webdriver import (
    WebDriverException,
    InvalidSwitchToTargetException,
    NoSuchWindowException,
    NoSuchFrameException,
    NoSuchElementException,
    NoSuchAttributeException,
    NoSuchShadowRootException,
    StaleElementReferenceException,
    InvalidElementStateException,
    UnexpectedAlertPresentException,
    NoAlertPresentException,
    ElementNotVisibleException,
    ElementNotInteractableException,
    ElementNotSelectableException,
    InvalidCookieDomainException,
    UnableToSetCookieException,
    TimeoutException,
    MoveTargetOutOfBoundsException,
    UnexpectedTagNameException,
    InvalidSelectorException,
    ImeNotAvailableException,
    ImeActivationFailedException,
    InvalidArgumentException,
    JavascriptException,
    NoSuchCookieException,
    ScreenshotException,
    ElementClickInterceptedException,
    InsecureCertificateException,
    InvalidCoordinatesException,
    InvalidSessionIdException,
    SessionNotCreatedException,
    UnknownMethodException,
    NoSuchDriverException,
    DetachedShadowRootException,
    UnknownCommandException,
)

__all__ = [
    "WebDriverException",
    "InvalidSwitchToTargetException",
    "NoSuchWindowException",
    "NoSuchFrameException",
    "NoSuchElementException",
    "NoSuchAttributeException",
    "NoSuchShadowRootException",
    "StaleElementReferenceException",
    "InvalidElementStateException",
    "UnexpectedAlertPresentException",
    "NoAlertPresentException",
    "ElementNotVisibleException",
    "ElementNotInteractableException",
    "ElementNotSelectableException",
    "InvalidCookieDomainException",
    "UnableToSetCookieException",
    "TimeoutException",
    "MoveTargetOutOfBoundsException",
    "UnexpectedTagNameException",
    "InvalidSelectorException",
    "ImeNotAvailableException",
    "ImeActivationFailedException",
    "InvalidArgumentException",
    "JavascriptException",
    "NoSuchCookieException",
    "ScreenshotException",
    "ElementClickInterceptedException",
    "InsecureCertificateException",
    "InvalidCoordinatesException",
    "InvalidSessionIdException",
    "SessionNotCreatedException",
    "UnknownMethodException",
    "NoSuchDriverException",
    "DetachedShadowRootException",
    "UnknownCommandException",
]
